# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivos', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEspecialidad',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Magnitud',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activo_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_eq', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('n_serie', models.CharField(max_length=30)),
                ('accesorios', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='imgs/inventario/QR/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgs/inventario/equipos/')),
                ('estatus', models.CharField(default='Activo', max_length=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.clasificacion')),
                ('id_direccion_esp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.direccionespecialidad', verbose_name='Direccion de especialidad')),
                ('id_magnitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.magnitud')),
            ],
        ),
    ]
