# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_equipo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_responsable_alta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_alta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='docs',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo'),
        ),
        migrations.AddField(
            model_name='docs',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipodoc'),
        ),
        migrations.AddField(
            model_name='baja',
            name='id_aprueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baja',
            name='id_equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo'),
        ),
    ]
