# Generated by Django 4.2.5 on 2023-12-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, null=True, upload_to='docs/inventario/')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
        migrations.DeleteModel(
            name='TipoDoc',
        ),
    ]
