# Generated by Django 4.2.5 on 2023-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_detalledocs_delete_docs_delete_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocs',
            name='url',
            field=models.FileField(upload_to='docs/inventario/'),
        ),
    ]
