# Generated by Django 4.2.5 on 2023-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detalledocs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocs',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='docs/inventario/'),
        ),
    ]
