# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionVerificacion',
            fields=[
                ('id_equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.equipo')),
                ('periodo', models.IntegerField()),
                ('ultima', models.DateField()),
                ('proxima', models.DateField()),
                ('estatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('num_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('puntoVer1', models.FloatField(null=True)),
                ('puntoVer2', models.FloatField(null=True)),
                ('puntoVer3', models.FloatField(null=True)),
                ('puntoVer4', models.FloatField(null=True)),
                ('puntoVer5', models.FloatField(null=True)),
                ('lecEq1', models.FloatField(null=True)),
                ('lecEq2', models.FloatField(null=True)),
                ('lecEq3', models.FloatField(null=True)),
                ('lecEq4', models.FloatField(null=True)),
                ('lecEq5', models.FloatField(null=True)),
                ('lecPatron1', models.FloatField(null=True)),
                ('lecPatron2', models.FloatField(null=True)),
                ('lecPatron3', models.FloatField(null=True)),
                ('lecPatron4', models.FloatField(null=True)),
                ('lecPatron5', models.FloatField(null=True)),
                ('errorVer1', models.FloatField(null=True)),
                ('errorVer2', models.FloatField(null=True)),
                ('errorVer3', models.FloatField(null=True)),
                ('errorVer4', models.FloatField(null=True)),
                ('errorVer5', models.FloatField(null=True)),
                ('dictamen', models.CharField(max_length=11)),
                ('doc', models.FileField(blank=True, null=True, upload_to='docs/verificacion')),
                ('id_aprobación', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprueba_verificacion', to=settings.AUTH_USER_MODEL)),
                ('id_patron', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.equipo')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_verificacion', to=settings.AUTH_USER_MODEL)),
                ('id_verificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verificacion.especificacionverificacion')),
            ],
        ),
    ]
