# Generated by Django 4.2.5 on 2023-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificacion', '0002_alter_especificacionverificacion_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/verificacion/'),
        ),
    ]
