# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('id_magnitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.magnitud')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionMetrologia',
            fields=[
                ('id_equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.equipo')),
                ('res_unidades', models.CharField(blank=True, max_length=25, null=True)),
                ('intervalo_medicion_unidades', models.CharField(max_length=30)),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrologia.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CriteriosMetrologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(choices=[('Max', 'Max'), ('Min', 'Min'), ('±', '±'), ('=', '=')], max_length=10)),
                ('id_criterio', models.CharField(max_length=20)),
                ('valor_esperado', models.CharField(max_length=100)),
                ('id_controlMetro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrologia.especificacionmetrologia')),
                ('id_unidad_criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrologia.unidad')),
            ],
        ),
    ]
