# Generated by Django 4.2.5 on 2023-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriosmetrologicos',
            name='valor_esperado',
            field=models.FloatField(),
        ),
    ]
