# Generated by Django 4.2.5 on 2023-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracion', '0004_alter_especificacioncalibracion_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioscalibracion',
            name='valor',
            field=models.FloatField(),
        ),
    ]
