# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMantenimientoExterno',
            fields=[
                ('num_folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('tipo_mant', models.CharField(max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='imgs/mantenimiento/evidencias/externo')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionMantenimiento',
            fields=[
                ('id_equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.equipo')),
                ('periodo', models.IntegerField()),
                ('tipo_periodo', models.CharField(choices=[('meses', 'meses'), ('horas', 'horas')], default='meses', max_length=10)),
                ('tiempo_uso', models.FloatField(blank=True, null=True)),
                ('ultima', models.DateField(blank=True, null=True)),
                ('proxima', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimientoInterno',
            fields=[
                ('num_folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_mant', models.CharField(max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='imgs/mantenimiento/evidencias/interno')),
                ('id_especificacion_mant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.especificacionmantenimiento')),
            ],
        ),
    ]
