# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemantenimientointerno',
            name='id_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_mant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallemantenimientointerno',
            name='id_responsable_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_captura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallemantenimientoexterno',
            name='id_especificacion_mant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.especificacionmantenimiento'),
        ),
        migrations.AddField(
            model_name='detallemantenimientoexterno',
            name='id_responsable_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
