# Generated by Django 4.2.5 on 2023-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionmantenimiento',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
    ]
